# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore Solution Dependencies
      run: cd src && dotnet restore
    - name: Build Solution Projects
      run: cd src && dotnet build DemoMVC.sln --no-restore
    - name: Install Playwright Browser
      run: cd src/DemoMVC.Tests && pwsh ./bin/Debug/net8.0/playwright.ps1 install
    - name: Test Project
      run: cd src && dotnet test --no-build --verbosity normal
